package name.zzhxufeng.wanandroid.ui.theme

import androidx.compose.ui.graphics.Color

val whitePrimary = Color(0xFF607D8B)
val whitePrimaryVariant = Color(0xFF455A64)
val whiteSecondary = Color(0xFF9E9E9E)
val whiteSecondaryVariant = Color(0xFF757575)
val whiteBackground = Color(0xFFFFFFFF)
val whiteSurface = Color(0xFFFFFFFF)
val whiteOnPrimary = Color(0xFFFFFFFF)
val whiteOnSecondary = Color(0xFFFFFFFF)
val whiteOnBackground = Color(0xFF212121)
val whiteOnSurface = Color(0xFF212121)

val primaryDark = Color(0xFF2B2B2B)
val secondaryDark = Color(0xFF323232)
val backgroundDark = Color(0xFF3C3F41)
val contentDark = Color(0xFF929292)

val orangePrimary = Color(0xFFFF9800)
val orangePrimaryVariant = Color(0xFFF57C00)
val orangeSecondary = Color(0xFFFF5722)
val orangeSecondaryVariant = Color(0xFFFFE0B2)
val orangeBackground = Color(0xFFFFFFFF)
val orangeSurface = Color(0xFFFFFFFF)
val orangeOnPrimary = Color(0xFFFFFFFF)
val orangeOnSecondary = Color(0xFFFFFFFF)
val orangeOnBackground = Color(0xFF212121)
val orangeOnSurface = Color(0xFF212121)

val bluePrimary = Color(0xFF00BCD4)
val bluePrimaryVariant = Color(0xFF0097A7)
val blueSecondary = Color(0xFF009688)
val blueSecondaryVariant = Color(0xFF00BCD4)
val blueBackground = Color(0xFFFFFFFF)
val blueSurface = Color(0xFFFFFFFF)
val blueOnPrimary = Color(0xFFFFFFFF)
val blueOnSecondary = Color(0xFFFFFFFF)
val blueOnBackground = Color(0xFF212121)
val blueOnSurface = Color(0xFF212121)
